---
title: Make a Party
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: contato.makeaparty@gmail.com
description: Make a Party
name: Igor Canedo e Caroline de Lima
author: Igor Canedo
baseurl: 
url: http://makeapartyscrap.com
gems:
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- node_modules
- gulpfile.js
- package.json
theme: jekyll-theme-cayman
