# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Make a Party
email: contato.makeaparty@gmail.com
description: Make a Party
name: Igor Canedo e Caroline de Lima
author: Igor Canedo

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://makeapartyscrap.com" # the base hostname & protocol for your site

# Gems
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json"]

theme: jekyll-theme-cayman